// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBynfaa2GdLEJN4DugESC5_uveIo0EPPMQ',
    appId: '1:830597327708:web:4ae1a23dc0a399741eaf99',
    messagingSenderId: '830597327708',
    projectId: 'smart-gate-f1f24',
    authDomain: 'smart-gate-f1f24.firebaseapp.com',
    databaseURL: 'https://smart-gate-f1f24-default-rtdb.firebaseio.com',
    storageBucket: 'smart-gate-f1f24.appspot.com',
    measurementId: 'G-RRFZCEC9BV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr-qr7QVP9c6zZNT902bQYsCVX8ylW8oI',
    appId: '1:830597327708:android:959ae24b456acf201eaf99',
    messagingSenderId: '830597327708',
    projectId: 'smart-gate-f1f24',
    databaseURL: 'https://smart-gate-f1f24-default-rtdb.firebaseio.com',
    storageBucket: 'smart-gate-f1f24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDWLKKI5zgNLY_rckz6eWfrlvvpUWMiE0',
    appId: '1:830597327708:ios:d0da0a4c1ebaca231eaf99',
    messagingSenderId: '830597327708',
    projectId: 'smart-gate-f1f24',
    databaseURL: 'https://smart-gate-f1f24-default-rtdb.firebaseio.com',
    storageBucket: 'smart-gate-f1f24.appspot.com',
    iosBundleId: 'com.example.smartGate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDWLKKI5zgNLY_rckz6eWfrlvvpUWMiE0',
    appId: '1:830597327708:ios:d0da0a4c1ebaca231eaf99',
    messagingSenderId: '830597327708',
    projectId: 'smart-gate-f1f24',
    databaseURL: 'https://smart-gate-f1f24-default-rtdb.firebaseio.com',
    storageBucket: 'smart-gate-f1f24.appspot.com',
    iosBundleId: 'com.example.smartGate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBynfaa2GdLEJN4DugESC5_uveIo0EPPMQ',
    appId: '1:830597327708:web:1153a60206450fdb1eaf99',
    messagingSenderId: '830597327708',
    projectId: 'smart-gate-f1f24',
    authDomain: 'smart-gate-f1f24.firebaseapp.com',
    databaseURL: 'https://smart-gate-f1f24-default-rtdb.firebaseio.com',
    storageBucket: 'smart-gate-f1f24.appspot.com',
    measurementId: 'G-B8Z4JF8NVB',
  );
}
